version: '3'

services:
  postgres:
    image: postgres:12.3
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=contacts
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql