version: '3'

services:
  postgres:
    image: postgres:12.3
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=contacts
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  contacts:
    build:
      context: .
    image: contacts
    container_name: contacts
    ports:
      - "8080:8080"
    depends_on:
      - postgres